# Generated by Django 4.1.5 on 2023-01-26 03:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("surname", models.CharField(max_length=50)),
                (
                    "card_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(9999999999999999)
                        ]
                    ),
                ),
                (
                    "card_cvv",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(999)]
                    ),
                ),
                (
                    "total_value",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(1000.0)]
                    ),
                ),
                ("extra_description", models.TextField(blank=True)),
                ("comission_value", models.FloatField()),
            ],
        ),
    ]
