# Generated by Django 4.1.5 on 2023-01-26 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_payment_card_cvv_alter_payment_card_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="comission_value",
        ),
    ]
