# Generated by Django 4.1.5 on 2023-01-26 04:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_alter_payment_card_cvv_alter_payment_card_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="card_number",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
