# Generated by Django 4.1.5 on 2023-01-26 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_alter_payment_card_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="card_cvv",
            field=models.IntegerField(
                validators=[django.core.validators.MinLengthValidator(3)]
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="card_number",
            field=models.BigIntegerField(
                validators=[django.core.validators.MinLengthValidator(16)]
            ),
        ),
    ]
