# Generated by Django 4.1.5 on 2023-01-26 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_alter_payment_card_cvv_alter_payment_card_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="card_cvv",
            field=models.TextField(
                validators=[django.core.validators.MinLengthValidator(3)]
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="card_number",
            field=models.TextField(
                validators=[django.core.validators.MinLengthValidator(16)]
            ),
        ),
    ]
