# Generated by Django 4.1.5 on 2023-01-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_alter_payment_card_cvv_alter_payment_card_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="comission_value",
            field=models.FloatField(default=0.0),
        ),
    ]
