# Generated by Django 4.1.5 on 2023-01-26 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_payment_comission_value"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="comission_value",
            new_name="commission_value",
        ),
    ]
