# Generated by Django 4.1.5 on 2023-01-26 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_rename_comission_value_payment_commission_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="card_number",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(16),
                    django.core.validators.RegexValidator(
                        regex="^(?:[0-9]{4}[ ]?){3}[0-9]{4}$"
                    ),
                ]
            ),
        ),
    ]
