# Generated by Django 4.1.5 on 2023-01-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0015_alter_payment_card_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="card_tipe",
            field=models.TextField(blank=True),
        ),
    ]
