# Generated by Django 4.1.5 on 2023-01-26 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0016_payment_card_tipe"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="card_tipe",
            new_name="card_type",
        ),
    ]
