# Generated by Django 4.1.5 on 2023-01-27 04:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0017_rename_card_tipe_payment_card_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="var",
            field=models.TextField(
                blank=True, validators=[django.core.validators.MinLengthValidator(1000)]
            ),
        ),
    ]
