# Generated by Django 4.1.5 on 2023-01-27 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0019_alter_payment_var"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="var",
        ),
    ]
