# Generated by Django 4.1.5 on 2023-01-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0020_remove_payment_var"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="var",
            field=models.TextField(blank=True),
        ),
    ]
