# Generated by Django 4.1.5 on 2023-01-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0024_alter_payment_var"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="var",
            new_name="response_Payu",
        ),
    ]
