# Generated by Django 4.1.5 on 2023-01-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0025_rename_var_payment_response_payu"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="order_num",
            field=models.TextField(null=True),
        ),
    ]
