# Generated by Django 4.1.5 on 2023-01-27 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0026_payment_order_num"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="order_num",
        ),
    ]
